name: CI Pipeline for Docker and Watchtower

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub runner for CI/CD pipeline

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install linters
      run: |
        npm install -g htmlhint stylelint
        sudo apt-get install -y hadolint

    - name: Lint HTML files
      run: htmlhint "**/*.html"

    - name: Lint CSS files
      run: stylelint "**/*.css"

    - name: Lint Dockerfile
      run: hadolint Dockerfile

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Logging in to Docker Hub..."
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        if [ -z "$DOCKER_USERNAME" ]; then
          echo "ERROR: DOCKER_USERNAME is not set!"; exit 1;
        fi
        echo "Using DOCKER_USERNAME: $DOCKER_USERNAME"

        IMAGE_NAME="$DOCKER_USERNAME/mywebapp:latest"

        docker build -t "$IMAGE_NAME" .
        docker push "$IMAGE_NAME"

    - name: SSH to server and update container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Connecting to server..."

          cd ~/Lab4

          git pull origin main

          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/mywebapp:latest"

          echo "Stopping old container..."
          docker stop mywebapp || true
          docker rm mywebapp || true

          echo "Pulling new image..."
          docker pull "$IMAGE_NAME"

          echo "Running new container..."
          docker run -d -p 80:80 --name mywebapp "$IMAGE_NAME"
